#!/bin/bash

BATTINFO=`acpi -b`
DISC=`echo $BATTINFO | grep Discharging`
CUT=`echo $BATTINFO | cut -f 4 -d " " | tr -d [:punct:]`

if [ "$DISC" = "" ]; then
  echo "Charging"
else
  if [ $CUT -lt 6 ]; then
    echo "hibernate"
    #sudo pm-hibernate
    mylock.sh &
    systemctl suspend
    #sudo pm-hibernate
  elif [ $CUT -lt 20 ]; then
    DISPLAY=:0.0 /usr/bin/notify-send "low battery" "$BATTINFO" -u critical -t 60000
  fi
fi 
